// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('prueba-registro', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('prueba-registro', async function() {
    await driver.get("https://www.cuestalibros.com/")
    await driver.manage().window().setRect({ width: 974, height: 1087 })
    {
      const element = await driver.findElement(By.css(".header-logo img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("small-searchterms")).click()
    await driver.findElement(By.id("small-searchterms")).click()
    {
      const element = await driver.findElement(By.linkText("Registrar"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Registrar")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("gender-female")).click()
    await driver.findElement(By.id("FirstName")).click()
    await driver.findElement(By.id("FirstName")).sendKeys("Saily")
    await driver.findElement(By.id("LastName")).sendKeys("Cabrera")
    await driver.findElement(By.id("Email")).sendKeys("saily.mcabrerasanchez@gmail.com")
    await driver.findElement(By.id("Company")).sendKeys("MiCasa")
    await driver.findElement(By.id("Email")).click()
    await driver.findElement(By.id("Email")).click()
    await driver.findElement(By.css(".inputs:nth-child(5)")).click()
    await driver.findElement(By.id("Email")).sendKeys("20210475@gmail.com")
    await driver.findElement(By.name("DateOfBirthDay")).click()
    {
      const dropdown = await driver.findElement(By.name("DateOfBirthDay"))
      await dropdown.findElement(By.xpath("//option[. = '3']")).click()
    }
    await driver.findElement(By.name("DateOfBirthMonth")).click()
    {
      const dropdown = await driver.findElement(By.name("DateOfBirthMonth"))
      await dropdown.findElement(By.xpath("//option[. = 'marzo']")).click()
    }
    await driver.findElement(By.name("DateOfBirthYear")).click()
    {
      const dropdown = await driver.findElement(By.name("DateOfBirthYear"))
      await dropdown.findElement(By.xpath("//option[. = '2004']")).click()
    }
    await driver.findElement(By.css(".fieldset:nth-child(2) .inputs")).click()
    await driver.findElement(By.id("Company")).sendKeys("none")
    await driver.findElement(By.id("Password")).click()
    await driver.findElement(By.id("Password")).sendKeys("rXF44ZV@yKwTRy")
    await driver.findElement(By.id("ConfirmPassword")).sendKeys("rXF44ZV@yKwTRy")
    await driver.switchTo().frame(0)
    await driver.findElement(By.css(".recaptcha-checkbox-border")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("register-button")).click()
  })
})
