// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('prueba-buscar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('prueba-buscar', async function() {
    await driver.get("https://www.cuestalibros.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1096 })
    await driver.findElement(By.id("small-searchterms")).click()
    await driver.findElement(By.id("small-searchterms")).sendKeys("Cuento de hadas")
    await driver.findElement(By.id("small-searchterms")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".item-box:nth-child(1) img")).click()
  })
})
